# Generated by Django 2.0.8 on 2021-07-26 06:17

from django.db import migrations, models
import django.utils.timezone
import helpers.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100, validators=[helpers.validators.name_validator, helpers.validators.is_alphabetic])),
                ('middle_name', models.CharField(blank=True, default='', max_length=100, validators=[helpers.validators.name_validator, helpers.validators.is_alphabetic])),
                ('last_name', models.CharField(max_length=100, validators=[helpers.validators.name_validator, helpers.validators.is_alphabetic])),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=6, null=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[helpers.validators.is_numeric_value])),
                ('image', models.ImageField(null=True, upload_to='profile/')),
                ('admin', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('is_obsolete', models.BooleanField(default=False)),
                ('dob', models.DateField(blank=True, null=True)),
                ('group', models.ManyToManyField(to='auth.Group')),
            ],
            options={
                'db_table': 'user',
                'ordering': ['-created_at'],
            },
        ),
    ]
