# Generated by Django 3.0.4 on 2020-04-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200403_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('A', 'All')], default='A', max_length=3),
        ),
    ]
