# Generated by Django 3.0.4 on 2020-08-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='product',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
