# Generated by Django 3.0.4 on 2020-08-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200805_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
