# Generated by Django 3.0.4 on 2020-08-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20200805_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='address',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productorder',
            name='name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productorder',
            name='ph_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productorder',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='total_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
