# Generated by Django 3.0.4 on 2020-08-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_productorder_product_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('A', 'All')], default='M', max_length=10),
        ),
    ]
