# Generated by Django 3.0.4 on 2020-08-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20200806_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'small'), ('M', 'medium'), ('L', 'large'), ('XL', 'xtra large')], default='M', max_length=10),
        ),
    ]
