# Generated by Django 3.0.4 on 2020-08-07 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20200807_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='category',
        ),
        migrations.RemoveField(
            model_name='model',
            name='brand',
        ),
    ]
