# Generated by Django 2.0.8 on 2021-07-27 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import helpers.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commonapp', '0003_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('opens_at', models.TimeField(null=True)),
                ('closes_at', models.TimeField(null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logo/')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phone_number', models.CharField(max_length=15, null=True, unique=True, validators=[helpers.validators.phone_number_validator, helpers.validators.is_numeric_value])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_affiliate', models.BooleanField(default=False)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('currency', models.CharField(max_length=10)),
                ('invoice_counter', models.PositiveIntegerField(default=0, editable=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('pan_number', models.CharField(default='', max_length=16)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='commonapp.Address')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company', to='commonapp.Category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'company',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_obsolete', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_user', to='company.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'company users',
                'db_table': 'company_user',
                'ordering': ['-created_at'],
            },
        ),
    ]
