# Generated by Django 2.0.8 on 2021-08-01 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='closes_at',
        ),
        migrations.RemoveField(
            model_name='company',
            name='opens_at',
        ),
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
    ]
