# Generated by Django 2.0.8 on 2021-08-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
