# Generated by Django 2.0.8 on 2022-03-23 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.BigIntegerField(verbose_name='Total Price')),
                ('order_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Order placed at')),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('IN_TRANSIT', 'in_transit'), ('COMPLETED', 'completed'), ('CANCELLED', 'cancelled')], default='PENDING', max_length=40, verbose_name='Order status')),
                ('customer_name', models.CharField(max_length=250)),
                ('customer_address', models.CharField(max_length=250)),
                ('customer_ph_no', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', related_query_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField(verbose_name='Price')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('isbn', models.CharField(max_length=13, verbose_name='ISBN')),
                ('total_price', models.BigIntegerField(verbose_name='Total Price')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='product.Product')),
            ],
        ),
    ]
