# Generated by Django 2.0.8 on 2022-03-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='product_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
