# Generated by Django 2.0.8 on 2022-03-23 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_productorder_product_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='price',
        ),
    ]
