# Generated by Django 2.0.8 on 2022-03-24 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_productorder_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='order.Order'),
        ),
    ]
