OTP_TYPES = {
    'USER_REGISTER':'USER_REGISTER',
    'CHANGE_PASSWORD':'CHANGE_PASSWORD',
    'CHANGE_PHONE_NUMBER': 'CHANGE_PHONE_NUMBER',
}


OTP_STATUS_TYPES = {
    'ACTIVE': 1,
    'INACTIVE':2,
    'EXPIRED':0,
}



MAX_LENGTHS = {
    'PHONE_NUMBER_EXT': 6,
    'PHONE_NUMBER': 15,
    'ADDRESS': 200,
    'NAME': 100,
    'OTP': 8,
    'CURRENCY_TYPE': 4,
    # 'PRODUCT_STATUS': 8,
    # 'ORDER_STATUS': 12,
    'OTP_TYPES': 20,
    'OTP_STATUS': 3,
    # 'PRODUCT_CAT_TYPE': 8,
    # 'FOOD_TYPE': 8,
    # 'PRODUCT_CAT_SUB_TYPE': 30,
    'EMAIL': 50,
    # 'VENDOR_TYPE': 15,
    # 'PRODUCT_TYPE': 15,
    # 'COUPON_TYPE': 10,
}



DEFAULTS = {
    'PHONE_NUMBER_EXT': '977',
    'MARITAL_STATUS': 'SINGLE',
    # 'CURRENCY_TYPE': CURRENCY_TYPES['NRS'],
    # 'PRODUCT_STATUS': PRODUCT_STATUS_TYPE['ACTIVE'],
    # 'ORDER_STATUS': ORDER_STATUS['NEW_ORDER'],
    'OTP_TYPES': OTP_TYPES['USER_REGISTER'],
    'OTP_STATUS':OTP_STATUS_TYPES['INACTIVE'],
    # 'ORDER_LINE_STATUS': ORDER_LINE_STATUS['NEW'],
    # 'PRODUCT_CAT_TYPE': PRODUCT_CAT_TYPE['FOOD'],
    'FOOD_TYPE': '',
    'PRODUCT_CAT_SUB_TYPE': '',
    'ADDRESS': '',
    'ACCOUNT_TYPE': 'GOOGLE',
    'PURCHASE_STATUS': 'ORDERED',
    # 'PAYMENT_CHOICES': PAYMENT_MODES['CASH'],
    # 'STOCK_TRANSACTION': STOCK_TRANSACTION['PURCHASE'],
    # 'POSITION': 'TOP',
    # 'VENDOR_TYPE': VENDOR_TYPE['RESTAURANT'],
    # 'PRODUCT_TYPE': PRODUCT_TYPE['MENU'],
    # 'UNIT': UNIT['DAY'],
    # 'COUPON_TYPE': COUPON_TYPE['PRODUCT'],
    # 'RESERVATION_TYPE': RESERVATION_TYPE['CHECKED_OUT']
}
